"""Emergency broadcast loop.

Flow:
1. Operator approves actions on dashboard → clicks APPROVE BROADCAST
2. POST /api/broadcast/approve  →  calls Qwen-VL (text-only) to generate PA script
3. TTS converts script → wav  (pyttsx3 if kokoro unavailable)
4. wav saved to evidence dir, returned as URL
5. Dashboard plays via <audio> tag + shows waveform animation
"""
from __future__ import annotations

import asyncio
import hashlib
import logging
import os
import tempfile
import time
from pathlib import Path
from typing import Any

import httpx

logger = logging.getLogger(__name__)

# Broadcast audio is saved here; served via /api/broadcast/latest
_BROADCAST_DIR = Path(os.environ.get("EVIDENCE_DIR", "/tmp/vespergrid_evidence")) / "broadcasts"
_BROADCAST_DIR.mkdir(parents=True, exist_ok=True)

_LATEST_WAV: Path | None = None
_LATEST_SCRIPT: str = ""


def _env(name: str, default: str | None = None) -> str | None:
    v = os.environ.get(name)
    return v if v not in (None, "") else default


# ─── PA Script Generation via LLM ────────────────────────────────────────────

_PA_SYSTEM_PROMPT = (
    "You are the site PA announcement system at an industrial LNG terminal. "
    "You receive a safety incident summary and generate a clear, calm, authoritative "
    "3-sentence emergency announcement. "
    "Rules: "
    "1. State the hazard and affected zone in sentence 1. "
    "2. Give the specific safe evacuation route in sentence 2. "
    "3. Tell workers what to avoid in sentence 3. "
    "Return ONLY the announcement text. No JSON, no commentary, no titles."
)


async def generate_pa_script(
    incident: str,
    location: str,
    approved_actions: list[str],
    wind_info: str = "",
) -> str:
    """Call Qwen-VL (text-only) to generate a PA announcement script.
    Falls back to a template if no LLM is configured."""
    base_url = _env("VLLM_BASE_URL", "")
    if not base_url:
        return _template_script(incident, location, approved_actions, wind_info)

    model = _env("VLLM_MODEL", "Qwen/Qwen2.5-VL-7B-Instruct")
    api_key = _env("VLLM_API_KEY", "vespergrid-local")
    timeout = float(_env("VLLM_TIMEOUT_SECONDS", "30"))

    actions_text = "; ".join(approved_actions[:3]) if approved_actions else "evacuate immediately"
    user_msg = (
        f"Incident: {incident}\n"
        f"Location: {location}\n"
        f"Wind: {wind_info or 'unknown'}\n"
        f"Approved response actions: {actions_text}\n"
        "Generate the PA announcement now."
    )

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": _PA_SYSTEM_PROMPT},
            {"role": "user", "content": user_msg},
        ],
        "temperature": 0.3,
        "max_tokens": 200,
    }
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}

    try:
        async with httpx.AsyncClient(timeout=timeout) as client:
            resp = await client.post(
                f"{base_url.rstrip('/').removesuffix('/v1')}/v1/chat/completions",
                json=payload,
                headers=headers,
            )
            resp.raise_for_status()
            script = resp.json()["choices"][0]["message"]["content"].strip()
            logger.info("PA script generated by LLM (%d chars)", len(script))
            return script
    except Exception as exc:
        logger.warning("LLM PA generation failed: %s — using template", exc)
        return _template_script(incident, location, approved_actions, wind_info)


def _template_script(
    incident: str, location: str, actions: list[str], wind_info: str
) -> str:
    action = actions[0] if actions else "evacuate via the north gate"
    wind = f" Wind is {wind_info}." if wind_info else ""
    return (
        f"Attention all personnel. A {incident.lower()} has been detected at {location}.{wind} "
        f"All workers in the affected zone must {action.lower()} immediately. "
        "Do not enter Sector 4 or the downwind vapor drift corridor until the all-clear is issued."
    )


# ─── TTS ─────────────────────────────────────────────────────────────────────

def _tts_to_wav(script: str, out_path: Path) -> bool:
    """Try kokoro-onnx first, fall back to pyttsx3, then espeak CLI."""
    # Try 1: pyttsx3 (most portable)
    try:
        import pyttsx3  # type: ignore
        engine = pyttsx3.init()
        engine.setProperty("rate", 155)
        engine.setProperty("volume", 0.95)
        engine.save_to_file(script, str(out_path))
        engine.runAndWait()
        if out_path.exists() and out_path.stat().st_size > 1000:
            logger.info("TTS via pyttsx3 → %s", out_path)
            return True
    except Exception as exc:
        logger.warning("pyttsx3 failed: %s", exc)

    # Try 2: espeak CLI (available on most Linux servers)
    try:
        import subprocess
        result = subprocess.run(
            ["espeak", "-s", "140", "-w", str(out_path), script],
            timeout=15, capture_output=True,
        )
        if result.returncode == 0 and out_path.exists() and out_path.stat().st_size > 500:
            logger.info("TTS via espeak → %s", out_path)
            return True
        logger.warning("espeak exit %d: %s", result.returncode, result.stderr)
    except Exception as exc:
        logger.warning("espeak failed: %s", exc)

    # Try 3: gTTS (requires internet, last resort)
    try:
        from gtts import gTTS  # type: ignore
        tts = gTTS(text=script, lang="en", slow=False)
        tts.save(str(out_path))
        if out_path.exists() and out_path.stat().st_size > 1000:
            logger.info("TTS via gTTS → %s", out_path)
            return True
    except Exception as exc:
        logger.warning("gTTS failed: %s", exc)

    logger.error("All TTS backends failed for broadcast")
    return False


# ─── Main entry point ─────────────────────────────────────────────────────────

async def approve_broadcast(
    incident: str,
    location: str,
    approved_actions: list[str],
    wind_info: str = "",
) -> dict[str, Any]:
    """Generate PA script, convert to wav, return metadata."""
    global _LATEST_WAV, _LATEST_SCRIPT

    script = await generate_pa_script(incident, location, approved_actions, wind_info)
    _LATEST_SCRIPT = script

    slug = hashlib.md5(script.encode()).hexdigest()[:8]
    wav_path = _BROADCAST_DIR / f"broadcast_{slug}.wav"

    loop = asyncio.get_event_loop()
    success = await loop.run_in_executor(None, _tts_to_wav, script, wav_path)

    if success:
        _LATEST_WAV = wav_path
        audio_url = f"/api/broadcast/latest"
    else:
        audio_url = None

    return {
        "script": script,
        "audio_url": audio_url,
        "tts_success": success,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }


def get_latest_wav() -> Path | None:
    return _LATEST_WAV


def get_latest_script() -> str:
    return _LATEST_SCRIPT
